### GET ALL EVENTS
GET http://localhost:3000/events

### Create Event
POST http://localhost:3000/events
Content-Type: application/json

{
  "name": "Evento 1",
  "description": "This is a new event",
  "price": 100,
  "date": "2024-06-17T00:00:00"
}
> {%
  client.global.set("eventId", response.body.id);
%}


### GET EVENT BY ID
GET http://localhost:3000/events/{{eventId}}

### Update Event
PATCH http://localhost:3000/events/{{eventId}}
Content-Type: application/json

{
  "name": "Evento 1 - Atualizado",
  "description": "This is a updated event",
  "price": 100,
  "date": "2024-06-17T00:00:00"
}

### Delete Event
DELETE http://localhost:3000/events/{{eventId}}


### GET ALL SPOTS
GET http://localhost:3000/events/{{eventId}}/spots

### Create Spot
POST http://localhost:3000/events/{{eventId}}/spots
Content-Type: application/json

{
  "name": "A4"
}

> {%
  client.global.set("spotName", response.body.name)
%}

### RESERVE SPOT
POST http://localhost:3000/events/{{eventId}}/reserve
Content-Type: application/json

{
  "spots": ["{{ spotName }}"],
  "ticket_kind": "full",
  "email": "test@test.com.br"
}